project_id = "axinziollxrrncuukhql"

[functions.market-data]
verify_jwt = false

[functions.ai-market-analysis]
verify_jwt = false

[functions.auth-callback]
verify_jwt = false

[functions.external-invite]
verify_jwt = false

[functions.interest-form]
verify_jwt = false
